[project]
name = "pong-grpo"
version = "0.1.0"
description = "Playing Atari Assault with GRPO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ale-py>=0.10.2",
    "gymnasium>=1.1.1",
    "torch>=2.6.0",
]
